---
title: "About"
---
## Fazeeia Mohammed
## Education

- **University of the West Indies**  
  B.Sc (Special) Computer Science  
  Upper Second Class Honours

- **University of the West Indies**  
  B.Sc Environmental and Natural Resource Management

## Experience

### Data Specialist - Sustainability (Full Time)  
*School of Business and Computer Science*  
*04/2024 - Present*

- Lead data collection initiatives for Environment Social and Governance (ESG) compliance with the Paris Agreement.
- Participated in co-ordination efforts for Business Forum.

### Lecturer (Part Time)  
*School of Business and Computer Science*  
*01/2024 - Present*

- Created course material for AI and Machine Learning for Business Professionals.
- Applied data science techniques for customer segmentation.

### Data Analyst (Full Time)  
*Rystad Energy*  
*10/2023 - 01/2024*

- Developed data-scrapers for curating data from government websites.
- Applied heuristics to features scraped from different sources.
- Ensured data validation and structured entity relationship diagrams for database.
- Expanded the data-set for wind energy generation modelling.

### Data Analyst (Full Time)  
*Digicel Group*  
*03/2022 - 10/2023*

- Extracted and analyzed customer data from Oracle SQL Database to identify non-revenue generating customers, resulting in a 40% increase in revenue activity within this group.
- Developed efficient data pipelines for processing and transforming large datasets.
- Proficiently manipulated Excel files for data integration and analysis.
- Created Financial Forecasting Models to predict revenue.
- Built CHURN prediction models to identify potential customer CHURN.

### Lead Technical Liaison (Full Time)  
*TTLAB collaboration with The Cropper Foundation*  
*08/2021 - 03/2022*

- Managed a team of 12 in the development of a mobile application for predicting water stress and crop damage.
- Utilized UAV for data collection and research on crop damage.
- Coordinated research project objectives and ensured successful delivery of project goals.
About this site
